name: Build and Test GEGL.wasm

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup Emscripten
      uses: mymindstorm/setup-emsdk@v14
      with:
        version: 3.1.50
        actions-cache-folder: 'emsdk-cache'

    - name: Setup Ninja
      run: |
        sudo apt-get update
        sudo apt-get install -y ninja-build

    - name: Cache build dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/meson
          subprojects/babl-*
          subprojects/poly2tri-c-*
          subprojects/libnsgif-*
        key: ${{ runner.os }}-build-deps-${{ hashFiles('subprojects/*.wrap') }}
        restore-keys: |
          ${{ runner.os }}-build-deps-

    - name: Build GEGL.wasm (Production)
      run: ./build-wasm.sh prod

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build JavaScript distributions
      run: npm run build:dist

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: gegl-wasm-build
        path: |
          build-wasm-prod/
          js/*.js
          js/*.d.ts
          dist/
          README.md
          COPYING
          COPYING.LESSER
          AUTHORS
        retention-days: 30

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: gegl-wasm-build
        path: .

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright browsers
      run: npx playwright install --with-deps

    - name: Run browser tests
      run: npm test

  publish:
    runs-on: ubuntu-latest
    needs: [build, test]
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: gegl-wasm-build
        path: .

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        registry-url: 'https://registry.npmjs.org'

    - name: Install dependencies
      run: npm ci

     - name: Publish to npm
       run: npm publish
       env:
         NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  release:
    runs-on: ubuntu-latest
    needs: [build, test]
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: gegl-wasm-build
        path: .

    - name: Create GitHub release
      uses: softprops/action-gh-release@v1
      with:
        body: |
          Automated release of GEGL.wasm ${{ github.ref_name }}

          ## Changes
          See the [changelog](https://github.com/durableprogramming/gegl.wasm/blob/main/ChangeLog) for details.

          ## Downloads
          - NPM package: `npm install gegl-wasm`
          - CDN: Available at https://cdn.jsdelivr.net/npm/gegl-wasm@${{ github.ref_name }}/
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}